debug: false
server:
  http:
    addr: 0.0.0.0:80
data:
  database:
    driver: sqlite3
    connection: ./data-new/answer.db
  cache:
    file_path: data-new/cache/cache.db
i18n:
  bundle_dir: data-new/i18n
service_config:
  upload_path: data-new/uploads
swaggerui:
  show: true
  protocol: http
  host: 127.0.0.1
  address: :80
ui:
  base_url: ""
